name: Build Electron App For Win

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-2019]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 18
         cache: npm # or pnpm / yarn

        # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app for win
      - name: build windows app
        if: matrix.os == 'windows-2019'
        run: |
          npm run electron:build-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step5: cleanup artifacts in release
      - name: cleanup artifacts
        run: |
          npx rimraf "release/!(*.exe)"

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: release

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
